"""empty message

Revision ID: 0992c9483ef8
Revises: 70f73ba6a519
Create Date: 2021-12-12 19:31:40.377304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0992c9483ef8'
down_revision = '70f73ba6a519'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_state', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp_creation', sa.DateTime(timezone=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_state', schema=None) as batch_op:
        batch_op.drop_column('timestamp_creation')

    # ### end Alembic commands ###
