"""empty message

Revision ID: 7569d9904914
Revises: a503ba5780c8
Create Date: 2021-10-27 21:25:10.854979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7569d9904914'
down_revision = 'a503ba5780c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matchmaker_request',
    sa.Column('timestamp_creation', sa.DateTime(timezone=128), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ranked', sa.Boolean(), nullable=True),
    sa.Column('min_rank', sa.Integer(), nullable=True),
    sa.Column('max_rank', sa.Integer(), nullable=True),
    sa.Column('time', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matchmaker_request')
    # ### end Alembic commands ###
