"""empty message

Revision ID: 7967fb1ea2f1
Revises: 8bfa691f55e2
Create Date: 2021-10-17 22:48:36.766616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7967fb1ea2f1'
down_revision = '8bfa691f55e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_host_white', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_column('is_host_white')

    # ### end Alembic commands ###
