"""empty message

Revision ID: a503ba5780c8
Revises: c390caaca794
Create Date: 2021-10-24 23:56:26.565265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a503ba5780c8'
down_revision = 'c390caaca794'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('show_eval_bar', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_column('show_eval_bar')

    # ### end Alembic commands ###
