"""empty message

Revision ID: aee2deb19dc0
Revises: 545401c927c1
Create Date: 2021-10-23 21:00:20.416268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aee2deb19dc0'
down_revision = '545401c927c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender_seen', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('receiver_seen', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('receiver_seen')
        batch_op.drop_column('sender_seen')

    # ### end Alembic commands ###
