"""empty message

Revision ID: c390caaca794
Revises: e06a976b2d6b
Create Date: 2021-10-24 23:24:58.578197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c390caaca794'
down_revision = 'e06a976b2d6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_state', schema=None) as batch_op:
        batch_op.add_column(sa.Column('en_passent', sa.String(length=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_state', schema=None) as batch_op:
        batch_op.drop_column('en_passent')

    # ### end Alembic commands ###
