"""empty message

Revision ID: fe6a7cb52767
Revises: 6b2b9001c0ac
Create Date: 2021-11-02 23:54:47.567745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe6a7cb52767'
down_revision = '6b2b9001c0ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('elo_user_rating',
    sa.Column('timestamp_creation', sa.DateTime(timezone=128), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rapid', sa.Integer(), nullable=True),
    sa.Column('blitz', sa.Integer(), nullable=True),
    sa.Column('standard', sa.Integer(), nullable=True),
    sa.Column('bullet', sa.Integer(), nullable=True),
    sa.Column('puzzles', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('elo_user_rating')
    # ### end Alembic commands ###
